language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9

before_install:
  - echo "Upgrading pip"
  - python3 -m pip install --upgrade pip
  - python3 -m pip install setuptools wheel twine
  - git clone https://github.com/TravisToolbox/bandit

install:
  - echo "Install project dependancies and requirements"
  - pip3 install codecov
  - pip3 install coverage
  - pip3 install pytest-cov
  - pip3 install pytest
  # - pip3 install -r requirements.txt
  - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  # Install the package from setup.py
  - python3 setup.py install
  - ./bandit/install.sh


script:
  - echo "Running AAIndex tests"
  # - python3 -m tests.test_aaindex
  # - coverage run --source
  - pytest --flake8
  # - pytest --pylint
  # - echo "Running model tests"
  - cd pySAR
  - python -m unittest discover tests -v
  - pytest --cov-report term --cov=investpy tests/
  - coverage run -m unittest discover -s tests -p 'test_*.py' #  OR"coverage run -m unittest discover -s . -p '*_unit_test.py'"
  - ./bandit/scan.sh

# python -m unittest discover -s tests -p "*_test.py" -v
after_success:
  # - codecov
  - coveralls
  - echo "Build success"

#Travis Toolkit with Bandit
# language: python
# rvm: 3.6
# before_install:
#   - git clone https://github.com/TravisToolbox/bandit
# install:
#   - ./bandit/install.sh
# script:
#   - ./bandit/scan.sh
